### ISSUE TITLE
change position of set in bed

### ISSUE THREAD

**Issue by Colourpieces** [coding-bootcamps-eu/final-project-tz-eden-sketch#63]
- button in plantbed edit view next to add button: activate position change
- 2 buttons show up: < and > (disabled. user has to click on a set)
- when user choosed a set to move < and > are able to use. when no alternative positions available --> show info message
- use function calculateStartColums
- move set to next possible position with < and >

**Comment by Colourpieces** [comment]
74298d0b05e1523f7e64bbfdb28f6ed2ee706368 includes everything for this issue but doesn't work at the moment. debugging is necessary.

**Comment by Colourpieces** [comment]
2 lösungsansätze:

option 1:
große umbauarbeiten:
in currentbed State array nicht die plantvariety ID sondern die Set id schreiben
-calculate Startcolums und alle folgenden funktionen (check if add set possible und isSpace usw)einen optionalen parameter mitgeben nämlich die setId. 
ziel: sich selbst ignorieren damit das startcolumsArray auch die durch das set belegten spalten mit aufnimmt

option 2:
set bei der moveset function rauslöschen aus dem bedplan startcolums berechnen und set wieder hinzufügen

option 1 ist die nachhaltigere und stabilere lösung... lösung 2 auf den ersten blick wahrscheinlich weniger arbeit aber verursacht auch viele (unnötige) funktionsaufrufe weil beim wieder hinzufügen ja auch wieder die ganzen checks durchlaufen usw....
im moment funktioniert set verschieben schon es überspringt nur im moment sich selbst. und wenn in einem beet noch 3 spalten frei sind (weniger als es braucht) muss es ja trotzdem zwischen den 3 positionen hin und her springen
ich bin für lösung 1.

**Comment by wiebken-n** [comment]
issue has been solved in #82
